name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Tests
        run: go test ./...

      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Executables
        run: |
          chmod +x ./cmd/markcli/build.sh
          ./cmd/markcli/build.sh
          cd dist
          # Rename binaries to include version
          mv markcli-linux markcli-linux-${{ env.VERSION }}
          mv markcli-mac markcli-mac-${{ env.VERSION }}
          mv markcli.exe markcli-windows-${{ env.VERSION }}.exe
          # Generate checksums
          sha256sum markcli-linux-${{ env.VERSION }} > markcli-linux-${{ env.VERSION }}.sha256
          sha256sum markcli-mac-${{ env.VERSION }} > markcli-mac-${{ env.VERSION }}.sha256
          sha256sum markcli-windows-${{ env.VERSION }}.exe > markcli-windows-${{ env.VERSION }}.exe.sha256

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/markcli-linux-${{ env.VERSION }}
            dist/markcli-mac-${{ env.VERSION }}
            dist/markcli-windows-${{ env.VERSION }}.exe
            dist/markcli-linux-${{ env.VERSION }}.sha256
            dist/markcli-mac-${{ env.VERSION }}.sha256
            dist/markcli-windows-${{ env.VERSION }}.exe.sha256
          draft: false
          prerelease: false
          generate_release_notes: true